### ISSUE TITLE
Wie mit Motorradstellplätzen umgehen?

### ISSUE THREAD

**Issue by wielandb** [wielandb/osm-parking-tagging#7]
(@SupaplexOSM in https://github.com/wielandb/osm-parking-tagging/issues/2 )

bei dem "motorcycle=designated"-Fall (also einem reinen Motorradstellplatz) haben wir das Problem, dass es dafür in OSM "amenity=motorcycle_parking" gibt... Müsste man dann also eigentlich den Primärkey ändern. Hier ein Beispiel, das ich gestern erst gemappt habe: https://www.openstreetmap.org/way/1119553883 (ignoriere einfach das "motorcycle_parking:position=lane"-Tagging, das ist wahrscheinlich überflüssig bzw. wir verwenden es bei Fahrradständern und ich hab es hier auf den Motorradstellplatz adaptiert...)

**Comment by SupaplexOSM** [comment]
Da sich das `amenity=motorcycle_parking` so in dieser Form nicht an der Straßenlinie umsetzen lässt, wäre es vielleicht eine pragmatische Variante, bei linien- und flächenhaft gemappten Parkplätzen verschiedene Tags zu nutzen. Also an der Straßenlinie `access=no` + `motorcycle=designated`, und an separaten Flächen `amenity=motorcycle_parking` (was die selben access-Tags implizieren müsste).

**Comment by wielandb** [comment]
Entsprechend umgesetzt
